version: "3"

services:
  pg-test:
    image: postgres:12
    # restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: xq-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password

  datastore:
    image: storytel/gcp-datastore-emulator
    command: start --testing --host=0.0.0.0 --port=8888
    ports:
      - "8888:8888"
