version: "3"

services:
  # datastore:
  #   image: singularities/datastore-emulator
  #   environment:
  #     - DATASTORE_PROJECT_ID=experquiz-next
  #     - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - /docker-data/test-ndb:/opt/data
  pg-test:
    image: postgres:12
    # restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: xq-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password
#    volumes:
#      - ./docker-data/test:/var/lib/postgresql/data:Z
#  web:
#    build:
#      context: .
#      dockerfile: web.Dockerfile
#    env_file: .env
#    environment:
#      - FLASK_ENV=development
#      - FLASK_RUN_HOST=0.0.0.0
#      - FLASK_RUN_PORT=8080
#    ports:
#      - "8080:8080"
#    volumes:
#    - .:/code
#  tests:
#    build:
#      context: .
#      dockerfile: tests.Dockerfile
#    environment:
#      - CI
#      - POSTGRES_DB=xq-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=pg-password
#    env_file: .env
#    volumes:
#    - .:/code

