name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ./src 
      - name: Test with pytest
        run: |
          pytest tests