name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    services:
      postgres:
        image: postgres:12.2-alpine
        # env:
        #   POSTGRES_USER: postgres
        #   POSTGRES_PASSWORD: postgres
        #   POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e . 
    - name: Test with pytest
      env: 
        POSTGRES_DB: xq-db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pg-password
      run: |
        pytest tests